from fastapi import APIRouter, Depends, HTTPException, Header, Request
from pydantic import BaseModel, Field
from typing import Any
import httpx
import hmac
import hashlib
from sqlalchemy.ext.asyncio import AsyncSession
from secumator.core import get_logger, settings
from secumator.core.database import get_db
from secumator.models.scan import Scan
from secumator.scanners.engine import ScanEngine

router = APIRouter()
logger = get_logger("api.github")


class GitHubScanRequest(BaseModel):
    repo_url: str = Field(..., description="GitHub repository URL")
    branch: str = Field(default="main", description="Branch to scan")
    scan_type: str = Field(default="webapp", description="Type of scan")
    create_pr_comment: bool = Field(default=True, description="Create PR comment with findings")
    pr_number: int | None = Field(default=None, description="PR number for comments")


class GitHubScanResponse(BaseModel):
    scan_id: int
    repo_url: str
    branch: str
    status: str


class GitHubWebhookPayload(BaseModel):
    action: str | None = None
    repository: dict[str, Any] | None = None
    pull_request: dict[str, Any] | None = None
    ref: str | None = None


def verify_github_signature(payload: bytes, signature: str, secret: str) -> bool:
    if not signature:
        return False
    expected = "sha256=" + hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


async def create_github_comment(
    repo: str, pr_number: int, body: str, token: str
) -> dict[str, Any] | None:
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    async with httpx.AsyncClient() as client:
        resp = await client.post(url, json={"body": body}, headers=headers, timeout=30.0)
        if resp.status_code == 201:
            return resp.json()
        logger.error("github_comment_failed", status=resp.status_code, body=resp.text)
        return None


async def create_check_run(
    repo: str, head_sha: str, name: str, status: str, conclusion: str | None, output: dict, token: str
) -> dict[str, Any] | None:
    url = f"https://api.github.com/repos/{repo}/check-runs"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {
        "name": name,
        "head_sha": head_sha,
        "status": status,
        "output": output,
    }
    if conclusion:
        payload["conclusion"] = conclusion
    
    async with httpx.AsyncClient() as client:
        resp = await client.post(url, json=payload, headers=headers, timeout=30.0)
        if resp.status_code == 201:
            return resp.json()
        logger.error("github_check_run_failed", status=resp.status_code, body=resp.text)
        return None


def format_findings_for_pr(findings: list[dict]) -> str:
    if not findings:
        return "## ✅ Security Scan Complete\n\nNo vulnerabilities found!"
    
    severity_icons = {
        "critical": "🔴",
        "high": "🟠",
        "medium": "🟡",
        "low": "🟢",
        "info": "ℹ️",
    }
    
    body = "## 🔒 Security Scan Results\n\n"
    body += f"Found **{len(findings)}** potential vulnerabilities:\n\n"
    
    by_severity = {}
    for f in findings:
        sev = f.get("severity", "info")
        if sev not in by_severity:
            by_severity[sev] = []
        by_severity[sev].append(f)
    
    for sev in ["critical", "high", "medium", "low", "info"]:
        if sev in by_severity:
            icon = severity_icons.get(sev, "")
            body += f"### {icon} {sev.upper()} ({len(by_severity[sev])})\n\n"
            for f in by_severity[sev][:5]:
                body += f"- **{f.get('title', 'Unknown')}**"
                if f.get("affected_component"):
                    body += f" - `{f['affected_component']}`"
                body += "\n"
                if f.get("recommendation"):
                    body += f"  - {f['recommendation']}\n"
            if len(by_severity[sev]) > 5:
                body += f"  - ... and {len(by_severity[sev]) - 5} more\n"
            body += "\n"
    
    body += "\n---\n*Generated by Secumator Security Scanner*"
    return body


@router.post("/github/scan", response_model=GitHubScanResponse)
async def scan_github_repo(request: GitHubScanRequest, db: AsyncSession = Depends(get_db)):
    repo_parts = request.repo_url.replace("https://github.com/", "").replace(".git", "").split("/")
    if len(repo_parts) < 2:
        raise HTTPException(status_code=400, detail="Invalid GitHub URL")
    
    target = request.repo_url
    
    scan = Scan(
        target=target,
        scan_type=request.scan_type,
        status="pending",
        profile="github-security",
    )
    db.add(scan)
    await db.commit()
    await db.refresh(scan)
    
    logger.info("github_scan_created", scan_id=scan.id, repo=request.repo_url)
    
    return GitHubScanResponse(
        scan_id=scan.id,
        repo_url=request.repo_url,
        branch=request.branch,
        status="pending",
    )


@router.post("/github/webhook")
async def github_webhook(
    request: Request,
    x_hub_signature_256: str | None = Header(None),
    x_github_event: str | None = Header(None),
    db: AsyncSession = Depends(get_db),
):
    body = await request.body()
    
    if settings.github_webhook_secret:
        if not verify_github_signature(body, x_hub_signature_256 or "", settings.github_webhook_secret):
            raise HTTPException(status_code=401, detail="Invalid signature")
    
    payload = await request.json()
    event = x_github_event or "unknown"
    
    logger.info("github_webhook_received", event=event)
    
    if event == "pull_request" and payload.get("action") in ["opened", "synchronize"]:
        pr = payload.get("pull_request", {})
        repo = payload.get("repository", {})
        
        repo_url = repo.get("html_url", "")
        pr_number = pr.get("number")
        head_sha = pr.get("head", {}).get("sha")
        
        if repo_url and pr_number:
            scan = Scan(
                target=repo_url,
                scan_type="webapp",
                status="pending",
                profile="github-pr-scan",
            )
            db.add(scan)
            await db.commit()
            await db.refresh(scan)
            
            logger.info("github_pr_scan_created", scan_id=scan.id, pr=pr_number)
            
            return {"status": "scan_queued", "scan_id": scan.id, "pr_number": pr_number}
    
    return {"status": "acknowledged", "event": event}


@router.post("/github/scan/{scan_id}/comment")
async def post_github_pr_comment(
    scan_id: int,
    pr_number: int,
    repo: str,
    token: str = Header(..., alias="X-GitHub-Token"),
    db: AsyncSession = Depends(get_db),
):
    from sqlalchemy import select
    from sqlalchemy.orm import selectinload
    
    result = await db.execute(
        select(Scan).options(selectinload(Scan.findings)).where(Scan.id == scan_id)
    )
    scan = result.scalar_one_or_none()
    
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")
    
    findings = [
        {
            "title": f.title,
            "severity": f.severity,
            "affected_component": f.affected_component,
            "recommendation": f.recommendation,
        }
        for f in scan.findings
    ]
    
    body = format_findings_for_pr(findings)
    result = await create_github_comment(repo, pr_number, body, token)
    
    if not result:
        raise HTTPException(status_code=500, detail="Failed to create comment")
    
    return {"status": "comment_created", "comment_id": result.get("id")}
